In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[2,5,3]])
arr

array([[1, 2, 3],
       [2, 5, 3]])

In [3]:
print(arr.ndim)

2


In [4]:
print(arr.shape)

(2, 3)


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.data)

# Statistical Funcitions

In [44]:
b = np.array([[20,32,11],[3,4,5],[7,4,4]])
print(b,"\n")

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 



In [8]:
b.dtype

dtype('int32')

In [9]:
b.itemsize

4

In [10]:
b.size

9

In [11]:
b.shape

(3, 3)

In [12]:
d = np.array([[20,32,11],[3,4,5],[7,4,4]], dtype=np.float64)
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize)

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

int32 

4


In [13]:
x = np.array([[1,3,4],[3,5,6],[3,4,7]], dtype=np.complex64)
y = np.array([[13,34,84],[54,77,90],[1,2,3]],dtype=np.complex128)
print(x,"\n")
print(x.dtype,"\n")
print(x.itemsize,"\n")
print(y,"\n")
print(y.dtype,"\n")
print(y.itemsize)

[[1.+0.j 3.+0.j 4.+0.j]
 [3.+0.j 5.+0.j 6.+0.j]
 [3.+0.j 4.+0.j 7.+0.j]] 

complex64 

8 

[[13.+0.j 34.+0.j 84.+0.j]
 [54.+0.j 77.+0.j 90.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j]] 

complex128 

16


In [14]:
print(np.sum(b))

90


In [15]:
print(b)

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]]


In [16]:
print(np.sum(b,axis=0))
print(np.sum(b,axis=1))

[30 40 20]
[63 12 15]


In [17]:
# 0 for columns
# 1 for rows

In [18]:
# Minimum Value
print(b,"\n")
print(np.amin(b),"\n")
print(np.amin(b,axis=0))
print(np.amin(b,axis=1))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

3 

[3 4 4]
[11  3  4]


In [19]:
# Maximum Value
print(b,"\n")
print(np.max(b),"\n")
print(np.max(b,axis=0))
print(np.max(b,axis=1),"\n")
print(type(b))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

32 

[20 32 11]
[32  5  7] 

<class 'numpy.ndarray'>


In [20]:
# Mean
print(b,"\n")
print(np.mean(b),"\n")
print(np.mean(b,axis=0))
print(np.mean(b,axis=1),"\n")
print(type(b))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

10.0 

[10.         13.33333333  6.66666667]
[21.  4.  5.] 

<class 'numpy.ndarray'>


In [21]:
# Standard Deviation
print(b,"\n")
print(np.std(b),"\n")
print(np.std(b,axis=0))
print(np.std(b,axis=1),"\n")
print(type(b))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

9.285592184789413 

[ 7.25718035 13.19932658  3.09120617]
[8.60232527 0.81649658 1.41421356] 

<class 'numpy.ndarray'>


In [22]:
# Median
print(b,"\n")
print(np.median(b),"\n")
print(np.median(b,axis=0))
print(np.median(b,axis=1),"\n")
print(type(b))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

5.0 

[7. 4. 5.]
[20.  4.  4.] 

<class 'numpy.ndarray'>


In [23]:
# Variance
print(b,"\n")
print(np.var(b),"\n")
print(np.var(b,axis=0))
print(np.var(b,axis=1),"\n")
print(type(b))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

86.22222222222223 

[ 52.66666667 174.22222222   9.55555556]
[74.          0.66666667  2.        ] 

<class 'numpy.ndarray'>


In [24]:
# Weighted Average
print(np.average(b))

10.0


In [25]:
c = np.array([2,3,4,1,2,5,6,7,8,8,9,4])
print(c)

[2 3 4 1 2 5 6 7 8 8 9 4]


In [26]:
weight = np.array([0.12,0.5,0.10,0.12,0.5,0.10,0.12,0.5,0.10,0.12,0.5,0.10])
print(weight)

[0.12 0.5  0.1  0.12 0.5  0.1  0.12 0.5  0.1  0.12 0.5  0.1 ]


In [27]:
print(np.average(c, weights=weight))

5.083333333333332


In [28]:
# Percentile
print(c,"\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(b,5,1))
print(np.percentile(b,5,0))

[2 3 4 1 2 5 6 7 8 8 9 4] 

1.55
1.88
[11.9  3.1  4. ]
[3.4 4.  4.1]


In [29]:
# Peak to Peak
# Max value - Min value
print(b,"\n")
print(c,"\n")
print(np.ptp(c,0))
print(np.ptp(b,0))
print(np.ptp(b,1))

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

[2 3 4 1 2 5 6 7 8 8 9 4] 

8
[17 28  7]
[21  2  3]


In [30]:
# Reshaping an array
print(b,"\n")
print(b.shape,"\n")
print(b.reshape(1,9),"\n")

[[20 32 11]
 [ 3  4  5]
 [ 7  4  4]] 

(3, 3) 

[[20 32 11  3  4  5  7  4  4]] 



# Slicing

In [31]:
e = [12,34,56,78,90]
print(e[0:3],"\n")

[12, 34, 56] 



In [32]:
# 2D Array
l = np.array([[23,45,67,23],[22,33,44,55],[1,2,3,4]])
print(l)

[[23 45 67 23]
 [22 33 44 55]
 [ 1  2  3  4]]


In [33]:
print(l[0,2])
print(l[1,3])
print(l[0:3,3])
print(l[-1,2:4])
print(l[0:3,1:3])

67
55
[23 55  4]
[3 4]
[[45 67]
 [33 44]
 [ 2  3]]


# Stacking

In [34]:
d = np.arange(12).reshape(3,4)
print(d,"\n")
f = np.arange(12,24).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [35]:
print(np.hstack((d,f)),"\n")
print(np.hstack((f,d)),'\n')

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [36]:
print(np.vstack((d,f)),'\n')
print(np.vstack((f,d)),'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



# Mathematical Operations

In [37]:
# Simple mathematical operations

# Random Number Generator using numpy

In [38]:
from numpy import random
x = random.randint(100)
print(x)

82


In [39]:
x = random.rand()
print(x)

0.03768657637205408


In [40]:
x = random.randint(100,size=(5))
print(x)

[58 17 30 45 56]


In [41]:
x = random.randint(100,size=(3,5))
print(x)

[[61 86 45 40 85]
 [19  3 59 62  9]
 [19 20 66 56 35]]


# 2.4 PRACTICAL: Creating scalars in Numpy

# 2.5 PRACTICAL: Creating vectors in Numpy

In [42]:
# string 
# ('1 2; 3 4')

In [43]:
# np.dot(max1,max2)